### ISSUE TITLE
SSL config not working with packages from EPEL

### ISSUE THREAD

**Issue by mihauck** [owncloud-ansible/apache#7]
Hi Robert,

i don't understand how to configure Apache ports listen with more than one port.
I need the following entry in my Apache config file

```
# Change this to Listen on specific IP addresses as shown below to 
# prevent Apache from glomming onto all bound IP addresses.
#
#Listen 12.34.56.78:80
Listen 80
Listen 443
```

In the defaults i have my ports configured e.g:

```
---
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
```

After looking at the tasks i understand there is a loop apache_ports_configuration_items  so i moved to the vars/ file

```
__apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
```

adding my apache_listen_ports_ssl is no solution, because apache_listen_port it get overwritten

```
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port_ssl }}"
```

Can you give me a hint?

My workaround was to alter the tasks and replace regexp with insertafter  

```
- name: Configure Apache
  lineinfile:
    dest: "{{ apache_port_conf_file }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ apache_ports_configuration_items }}"
  notify: __apache_restart
```
so in my vars file i do this
```
__apache_ports_configuration_items:
  - insertafter: "^Listen "
    line: "Listen {{ apache_listen_port }}"
  - insertafter: "^Listen {{ apache_listen_port }}"
    line: "Listen {{ apache_listen_port_ssl }}"
```

**Comment by xoxys** [comment]
@mihauck could you share your overwritten variables to use packages from EPEL?

**Comment by mihauck** [comment]
> @mihauck could you share your overwritten variables to use packages from EPEL?

#### host_vars
```
---
apache_packages:
- httpd
- mod_ssl
apache_server_root: /etc/httpd
apache_default_vhost_name: ssl.conf
apache_service: httpd
apache_conf_path: /etc/httpd/conf.d
apache_port_conf_file: /etc/httpd/conf/httpd.conf
...
```

**Comment by mihauck** [comment]
I installed a REHL Testserver, because the server i discoved the problem is a bad example and not suitable for our needs

The problem occurs with either httpd24 from software collections and httpd from rehl-server-rpms.
As soon as the default vhost ssl.conf is removed, the httpd does not listen to 443 anymore after a restart.

###  package httpd
#### OS
```
[owncloud@owncloud-randd ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.8 (Maipo)
Release:	7.8
Codename:	Maipo
```
#### repo 
```
[root@owncloud-randd etc]# yum info httpd
Geladene Plugins: product-id, search-disabled-repos, subscription-manager
Verfügbare Pakete
Name       : httpd
Architektur : x86_64
Version    : 2.4.6
Ausgabe    : 93.el7
Größe : 1.2 M
Quelle      : rhel-7-server-rpms/7Server/x86_64
Zusammenfassung: Apache HTTP Server
URL        : http://httpd.apache.org/
Lizenz      : ASL 2.0
Beschreibung: The Apache HTTP Server is a powerful, efficient, and extensible
            : web server.
```

#### host_vars
```
---
apache_packages:
- httpd
- mod_ssl
apache_server_root: /etc/httpd
apache_default_vhost_name: ssl.conf
apache_service: httpd
apache_conf_path: /etc/httpd/conf.d
apache_port_conf_file: /etc/httpd/conf/httpd.conf
...
```

##### group_vars
```
---
apache_listen_ip: "94.130.97.142"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_vhost_name: "10_test123.owncloud.works._ssl.conf"
apache_vhosts:
  - servername: "test123.owncloud.works"
    documentroot: "/var/www/owncloud"
    extra_parameters:
      - "Redirect / https://test123.owncloud.works"
      - "Errorlog /var/log/httpd/test123.owncloud.works.error.log"
      - "Customlog /var/log/httpd/test123.owncloud.works.access.log combined"

apache_vhosts_ssl:
  - servername: "test123.owncloud.works"
    documentroot: "/var/www/owncloud"
    certificate_file: "/etc/ssl/certs/self.cert.cert"
    certificate_key_file: "/etc/ssl/self.cert.key"
    extra_parameters:
      - "Errorlog /var/log/httpd/test123.owncloud.works_ssl.error.log"
      - "Customlog /var/log/httpd/test123.owncloud.works_ssl.access.log combined"

...
```


### package httpd24 
#### repo
```
[root@owncloud-randd httpd]# yum info httpd24
Geladene Plugins: product-id, search-disabled-repos, subscription-manager
Installierte Pakete
Name       : httpd24
Architektur : x86_64
Version    : 1.1
Ausgabe    : 19.el7
Größe : 0.0  
Quelle      : installed
Aus Quelle  : rhel-server-rhscl-7-rpms
Zusammenfassung: Package that installs httpd24
Lizenz      : GPLv2+
Beschreibung: This is the main package for httpd24 Software Collection.
```

####host_vars

default nothing changed


####group_vars 
see above
